version: '2'
services:
    node:
        image: node:0.12-wheezy
        container_name: node
        restart: always
        ports:
         - "3000:3000"
        volumes:
            - ./volumes/app:/mean
        tty: true

    mongo:
        image: mongo:3.0
        container_name: mongo
        restart: always
        ports:
         - "27017:27017"

